name: Typecheck

on: [push]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Typecheck
        run: yarn typecheck
